# Generated by Django 3.1.7 on 2021-04-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210305_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
